# Generated by Django 6.0.1 on 2026-02-20 10:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='title',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='completed_at',
            new_name='date_completed',
        ),
        migrations.RenameField(
            model_name='issues',
            old_name='created_at',
            new_name='date_reported',
        ),
        migrations.RemoveField(
            model_name='service',
            name='actual_service_date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='company',
        ),
        migrations.RemoveField(
            model_name='service',
            name='completion_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='running_cost',
        ),
        migrations.AddField(
            model_name='issues',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reported_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issues',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issues',
            name='cost',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='assigned_by',
            field=models.ForeignKey(default='3fa85f64-5717-4562-b3fc-2c963f66afa6', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_services_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='assigned_to',
            field=models.ForeignKey(default='3fa85f64-5717-4562-b3fc-2c963f66afa6', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_services_to', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='service',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='sla_status',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='sla_time',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='average_speed',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='battery_used',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='cost',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='end_location',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='start_location',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclestats',
            name='charging_time',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclestats',
            name='is_charging',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclestats',
            name='total',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChargeHistory',
            fields=[
                ('charge_id', models.AutoField(primary_key=True, serialize=False)),
                ('charge_date', models.DateTimeField()),
                ('charge_start_time', models.DateTimeField()),
                ('charge_end_time', models.DateTimeField()),
                ('energy_added_kwh', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_history', to='users.vehicle')),
            ],
        ),
    ]
