# Generated by Django 4.2.27 on 2026-03-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargehistory',
            name='charge_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='chargehistory',
            name='charge_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='chargehistory',
            name='charge_start_time',
            field=models.TimeField(),
        ),
    ]
